### ISSUE TITLE
Inconsistent results when changing node category with identifier

### ISSUE THREAD

**Issue by maximusunc** [biothings/biothings.api#223] opened 2022-05-02 16:01 UTC
Given the following query, I'm receiving inconsistent results when changing the category of n02 Xerostomia (HP:0000217). If I send the query as-is, I get two answers, Amylases and IRF5. If I remove the category completely or make it more specific (PhenotypicFeature, according to the [Node Normalizer](https://nodenormalization-sri.renci.org/docs)), then I only get Amylases. Maybe this is more of an overall architectural question, as Aragorn does something different in that it ignores any given category and sends the most specific category from the normalizer.

```
query={
    "message": {
      "query_graph": {
        "edges": {
          "e00": {
            "subject": "n00",
              "object": "n01",
          "predicates":["biolink:related_to"]
          },
          "e01": {
            "subject": "n01",
              "object": "n02",
          "predicates":["biolink:related_to"]
          }
        },
        "nodes": {
          "n00": {
            "ids": ["PUBCHEM.COMPOUND:644073"],
            "categories": ["biolink:ChemicalEntity"]
          },
          "n01": {
              "categories": ["biolink:Gene"]
          },
          "n02": {
            "ids": ["HP:0000217"],
            "categories": ["biolink:DiseaseOrPhenotypicFeature"]
          }
        }
      }
    }
  }
```

Related to: https://github.com/ranking-agent/strider/issues/363

**Comment by tokebe** [comment] 2022-05-02 17:30
@maximusunc This appears to be an issue with BTE -- I've made [an issue](https://github.com/biothings/BioThings_Explorer_TRAPI/issues/444) in the proper repository referencing this one where additional discussion may be directed. We're investigating and will update when we've localized the cause.

**Comment by newgene** [comment] 2022-05-03 18:24
closing this issue now, since it has been moved to the proper repository.

**Closed by newgene** 2022-05-03 18:24 UTC
