### ISSUE TITLE
"MongoClient opened before fork. Create MongoClient only " warning when running hub jobs

### ISSUE THREAD

**Issue by newgene** [biothings/biothings.api#172] opened 2021-07-29 20:21 UTC
One example, under mychem hub, when triggering an upload job, hub logs show this warning msg many times. Does not seem causing any real issue so far, but should still be fixed.

**Comment by namespacestd0** [comment] 2021-07-29 20:38
duplicate of #46

**Closed by namespacestd0** 2021-07-29 20:38 UTC
Labels: enhancement
